### PR TITLE
Add continuous Integration using Azure pipelines  

### PR DESCRIPTION
**Pull request by LukeLange1s**

### CODE REVIEW

**Review by abaga129 — APPROVED** [review]
Looks good to me

**Review by kaburkett — APPROVED** [review]
This looks like it will build the project.

**Comment by kaburkett** [comment]
We could also try the actions tab for continuous integration.

**Review by smithandrewl — APPROVED** [review]

**Comment by kaburkett** [comment]
It looks like this should get us set up with DevOps: 
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml

**Comment by abaga129** [comment]
I forgot about the actions tab.  It would be cool to see how it works.

**Pull request merged**
